import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://firstmail.ltd/webmail/login/');
  await page.getByRole('button', { name: 'To accept' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('jillmahle1953@ttattdo.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('plpaferrA!8097');
  await page.locator('#login-form-desktop > .flex.items-center.justify-between > .flex').click();
  await page.getByRole('button', { name: 'Log in webmail' }).click();
  await page.goto('https://firstmail.ltd/webmail/');
  await page1.goto('https://dreamina.capcut.com/ai-tool/home');
  await page1.getByText('Sign in').click();
  await page1.locator('div').filter({ hasText: /^Continue with email$/ }).nth(1).click();
  await page1.getByRole('textbox', { name: 'Enter email' }).click();
  await page1.getByRole('textbox', { name: 'Enter email' }).fill('jillmahle1953@ttattdo.com');
  await page1.getByRole('textbox', { name: 'Enter password' }).click();
  await page1.getByRole('textbox', { name: 'Enter password' }).fill('plpaferrA!8097');
  await page1.getByText('Sign up').click();
  await page1.getByRole('textbox', { name: 'Enter password' }).click();
  await page1.getByRole('textbox', { name: 'Enter password' }).fill('plpaferrA!8097');
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page.goto('https://firstmail.ltd/webmail/');
  await page.locator('div').filter({ hasText: 'Dreamina <dreamina@mail.' }).nth(3).click();
  await page1.getByRole('textbox').filter({ hasText: /^$/ }).fill('Q2GF52');
  await page1.getByRole('textbox', { name: 'Year' }).click();
  await page1.getByRole('textbox', { name: 'Year' }).fill('1987');
  await page1.getByText('Month').click();
  await page1.getByRole('option', { name: 'April' }).click();
  await page1.getByText('Day', { exact: true }).click();
  await page1.getByRole('option', { name: '5', exact: true }).click();
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByText('Other (please specify)').click();
  await page1.getByRole('button', { name: 'Continue to Dreamina' }).click();
  await page1.locator('.app-download-container-hnrVXj > img').click();
  await page1.locator('.close-button-bXf1SB > svg').click();
  await page1.getByRole('menuitem', { name: 'Try for A$0' }).getByRole('img').click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByText('Upgrade').nth(1).click();
  const page2 = await page2Promise;
  await page2.goto('https://f-p.sgsnssdk.com/obj/pipo-checkout-sg/pipo/fe/payin_checkout/pipoux_checkout/1001578/agreement-cashier.html?idc=sg&theme=dreamina&merchant_id=11202402DjWkb2&abParams=%7B%7D&improveAuth=1&fp_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFuZGFyZF9jbGFpbXMiOnsiZXhwIjoxNzc2MDAxNjAwLCJqdGkiOiJBVUFBQU50MmFRR0F3RUdva0FIQjZmajEyZEVLIiwiaWF0IjoxNzc1NjU2MDAwfSwia2luZiI6eyJrdHAiOiJLTVNWMl9TSUdOX0tFWSJ9LCJtYWluYWN0IjoiMTEyMDI0MDJEaldrYjIiLCJzdWJhY3QiOiI3NjI2Mzg0MjM1MTY2NzQ1NjAxIiwidWlkIjoiQXdGdjZxVUVjMDlTaVk0WXZIZXJsUjlTb1dpY2dBIiwicm8iOiJBRE1JTiIsInNjIjoiUEFZSU5fVU5JRklFRF9IUF9BR1JFRU1FTlRQQVkiLCJ0IjoxfQ.Z-gt24CERlYfyT2p_Tyf5kFjfqoohU9sMnsJxOsvLyE&fp_scene_tn=AUEAAPD2OGnnWkKHsRG7u99KWJ5AK&app_id=513641&pre_order_id=202604080319900010000AztLLRjCFjS&locale=en#');
  await page2.getByText('PayPal').click();
  await page2.getByRole('button', { name: 'Pay A$' }).click();
  await page2.getByRole('button', { name: 'Got it' }).click();
  await page2.locator('.pipo-radio-mask').first().click();
  await page2.getByRole('textbox', { name: 'Enter card number' }).click();
  await page2.getByRole('textbox', { name: 'Enter card number' }).fill('4938 7513 4163 3383');
  await page2.getByRole('textbox', { name: 'Full name' }).click();
  await page2.getByRole('textbox', { name: 'Full name' }).fill('SteuberKelly');
  await page2.getByRole('textbox', { name: 'MM/YY' }).click();
  await page2.getByRole('textbox', { name: 'MM/YY' }).fill('03/28');
  await page2.getByRole('textbox', { name: 'CVV/CVC' }).click();
  await page2.getByRole('textbox', { name: 'CVV/CVC' }).fill('262');
  await page2.getByRole('button', { name: 'Pay A$' }).click();
  await page2.getByRole('button', { name: 'Got it' }).click();
  await page1.locator('.closeBtn-fY0zUu').click();
  await page1.locator('.closeBtn-YgWvEz').click();
});